name: "Publish package"

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Create npmrc and save auth token to npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Install Deps
        run: npx lerna bootstrap

      - name: Test
        run: npx lerna run test

      - name: Publish new version to NPM
        run: npx lerna publish from-package --no-git-tag-version --no-push --yes --loglevel verbose --no-verify-access

