name: "Publish package"

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Deps
        run: yarn

      - name: Test
        run: yarn test

      - name: Publish new version to NPM
        run: npx lerna publish from-package --no-git-tag-version --no-push --yes --loglevel verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
